
export const actionType = {
    SET_JOBS : "SET_JOBS",
    SELECTED_JOB: "SELECTED_JOB",
    REMOVE_SELECTED_JOB:  "REMOVE_SELCTED_JOB",
    MAKE_REQEUEST : "MAKE_REQUEST",
    REGISTER_START : "REGISTER_START",
    REGISTER_SUCESS : "REGISTER_SUCCESS",
    REGISTER_FAIL: "REGISTER_FAIL",
    GOOGLE_SIGN_IN_START : "GOOGLE_SIGN_IN_START",
    GOOGLE_SIGN_IN_SUCESS : "GOOGLE_SIGN_IN_SUCESS",
    GOOGLE_SIGN_IN_FAIL : "GOOGLE_SIGN_IN_FAIL",
 }

